apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template: #POD
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:1.14.2 #image of app
        ports:
        - containerPort: 80
        volumeMounts: #volume mounted to container
          - name: secret-conn
            mountPath: /etc/secret

      volumes:  #volume mounted to pod
        - name:  secret-conn
          secret:
            secretName: mysecret
      resources:
        requests:
          cpu: 500m
        limits:
          cpu: 1000m
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      NodePort: 30000